name: Build arm64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies and set up repositories
        run: |
          sudo apt-get update
          sudo apt-get install -y curl gpg ca-certificates
          sudo update-ca-certificates

          # Add Kali GPG key using keyring
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://archive.kali.org/archive-key.asc | gpg --dearmor | sudo tee /etc/apt/keyrings/kali-archive-keyring.gpg > /dev/null

          # Add Kali repository
          echo "deb [trusted=yes] http://http.kali.org/kali kali-rolling main contrib non-free" | sudo tee /etc/apt/sources.list.d/kali.list

          # Add Droidian GPG key using keyring
          curl -fsSL https://repo.droidian.org/droidian-archive-keyring.gpg | sudo tee /etc/apt/keyrings/droidian-archive-keyring.gpg > /dev/null

          # Add Droidian repository
          echo "deb [trusted=yes] https://production.repo.droidian.org trixie main" | sudo tee /etc/apt/sources.list.d/droidian.list

          sudo apt-get update

          # Install all required build dependencies
          sudo apt-get install -y wget proot tar xz-utils curl git uml-utilities debootstrap sudo python3 python3-pip zip unzip aria2 patchelf axel dos2unix zstd squashfs-tools busybox \
            android-sdk-libsparse-utils yq debos bmap-tools

      - name: Run build script
        run: |
          chmod +x ./build.sh
          sudo ./build.sh -t qcom

      - name: Upload rootfs.img artifact
        if: success() && (hashFiles('rootfs.img') != '')
        uses: actions/upload-artifact@v4
        with:
          name: rootfs-arm64
          path: rootfs.img
