name: Build arm64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          # Add missing GPG keys for Kali and Mobian repositories
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 827C8569F2518CC677FECA1AED65462EC8D5E4C5 || true
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 970B1DD5FF63506F85001159951D61F2BC232697 || true
          # Ensure CA certificates are up to date for SSL
          sudo apt-get install -y ca-certificates
          # Continue with regular dependencies
          sudo apt-get install -y wget proot tar xz-utils curl git uml-utilities debootstrap sudo python3 python3-pip zip unzip aria2 patchelf axel dos2unix zstd squashfs-tools busybox \
            android-sdk-libsparse-utils yq debos bmap-tools

      - name: Run build script
        run: |
          chmod +x ./build.sh
          sudo ./build.sh -t qcom

      - name: Upload rootfs.img artifact
        if: success() && (hashFiles('rootfs.img') != '')
        uses: actions/upload-artifact@v4
        with:
          name: rootfs-arm64
          path: rootfs.img
